# reasonable parameters to find planes of @Work workspaces
transform:
    filter_field_name: z
    filter_limit_min: -0.1
    filter_limit_max: 2.0
    output_frame: /base_link
voxel_filter:
    leaf_size: 0.02
    filter_field_name: z
    filter_limit_min: 0.2 #0.2 filter out the floor if you don't need to recognize objects from the floor
    filter_limit_max: 1.2 # height of the object
passthrough_x:
    filter_field_name: x
    filter_limit_min: -1.0
    filter_limit_max: 1.0 #2.0 for the ERL_Lisbon_2017
passthrough_y:
    filter_field_name: y
    filter_limit_min: -1.0
    filter_limit_max: 1.0
normal_estimation:
    k_search: 0
    radius_search: 0.03
    spatial_locator: 0
planar_segmentation:
    model_type: 11        # try 11 if not working
    distance_threshold: 0.01
    max_iterations: 1000
    method_type: 0
    eps_angle: 0.09
    optimize_coefficients: true
    axis: [0.0, 0.0, 1.0]
    normal_distance_weight: 0.05
project_plane_inliers:
    model_type: 11
    copy_all_data: false
    copy_all_fields: true
    approximate_sync: true
statistical_outlier_removal:
    stddev: 5.0
    mean_k: 30

# model types for planar_segmentation
# 0: SACMODEL_PLANE
# 1: SACMODEL_LINE
# 2: SACMODEL_CIRCLE2D
# 3: SACMODEL_CIRCLE3D
# 4: SACMODEL_SPHERE
# 5: SACMODEL_CYLINDER
# 6: SACMODEL_CONE
# 7: SACMODEL_TORUS
# 8: SACMODEL_PARALLEL_LINE
# 9: SACMODEL_PERPENDICULAR_PLANE
# 10: SACMODEL_PARALLEL_LINES
# 11: SACMODEL_NORMAL_PLANE
# 12: SACMODEL_NORMAL_SPHERE
# 13: SACMODEL_REGISTRATION
# 14: SACMODEL_REGISTRATION_2D
# 15: SACMODEL_PARALLEL_PLANE
# 16: SACMODEL_NORMAL_PARALLEL_PLANE
# 17: SACMODEL_STICK
